services:
  vllm:
    image: vllm/vllm-openai:latest
    command: |
      --model $MODEL
      ${EXTRA_ARGS:-""}
    ports:
      - "8000:8000"
    volumes:
      - vllm-cache:/root/.cache/huggingface
    environment:
      - HUGGING_FACE_HUB_TOKEN=${HUGGING_FACE_HUB_TOKEN:-""}
    restart: unless-stopped
    shm_size: 1g
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    environment:
      - OPENAI_API_BASE_URL=http://vllm:8000/v1
      - OPENAI_API_KEY=""
    ports:
      - "8080:8080"
    depends_on:
      - vllm

volumes:
  vllm-cache:
