services:
  vllm:
    restart: unless-stopped
    image: vllm/vllm-openai:latest
    command: |
      --model $MODEL
      ${EXTRA_ARGS:-""}
    ports:
      - "8000:8000"
    volumes:
      - vllm-cache:/root/.cache/huggingface
    environment:
      - HUGGING_FACE_HUB_TOKEN=${HUGGING_FACE_HUB_TOKEN:-""}
    shm_size: 1g
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 10s

  open-webui:
    restart: unless-stopped
    image: ghcr.io/open-webui/open-webui:main
    environment:
      - OPENAI_API_BASE_URL=http://vllm:8000/v1
      - OPENAI_API_KEY=""
    volumes:
      - open-webui:/app/backend/data
    ports:
      - "8080:8080"
    depends_on:
      vllm:
        condition: service_healthy

volumes:
  vllm-cache:
  open-webui:
