version: '3.9'

services:
  kafka:
    image: wurstmeister/kafka:2.12-2.5.1
    restart: unless-stopped
    environment:
      KAFKA_LISTENERS: INTERNAL://:9092,EXTERNAL://:19092
      # use localhost for clients outside of kafka container's network
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://localhost:19092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: test:1:1,test1:1:1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
    ports:
      - "19092:19092"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "kafka-topics.sh --list --bootstrap-server localhost:9092 | grep -q 'test' || exit 1"
        ]
      interval: 5s
      timeout: 10s
      retries: 5
    depends_on:
      - zookeeper
  zookeeper:
    image: zookeeper:3.7.1
    restart: unless-stopped

  consumer:
    image: sko00o/go-toolbox:latest
    entrypoint: kafka-cli
    # make localhost refer to the docker host
    network_mode: host
    command: |
      consumer -k localhost:19092 -t test -s first
    depends_on:
      kafka:
        condition: service_healthy

  producer:
    image: sko00o/go-toolbox:latest
    entrypoint: kafka-cli
    # make localhost refer to the docker host
    network_mode: host
    command: |
      producer -k localhost:19092 -t test
    depends_on:
      kafka:
        condition: service_healthy
