services:
  kafka:
    image: wurstmeister/kafka:2.12-2.5.1
    restart: unless-stopped
    environment:
      # set `remote-host` as kafka external host
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://remote-host:19092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LISTENERS: INTERNAL://:9092,EXTERNAL://:19092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: test:1:1,test1:1:1,test2:1:1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
    ports:
      - "19092:19092"
    healthcheck:
      # check multi topics exist
      test:
        [
          "CMD-SHELL",
          "kafka-topics.sh --list --bootstrap-server localhost:9092 | awk 'BEGIN { count=0 } /^test$|^test1$|^test2$/ { count++ } END { exit (count == 3) ? 0 : 1 }'"
        ]
      interval: 5s
      timeout: 10s
      retries: 10
    depends_on:
      zookeeper:
        condition: service_healthy

  zookeeper:
    restart: unless-stopped
    image: zookeeper:3.7.1
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "echo stat / | zkCli.sh -server 127.0.0.1:2181"
        ]
      interval: 5s
      timeout: 10s
      retries: 10
