global:
  scrape_interval: 15s
scrape_configs:
  - job_name: "kafka-exporter"
    scrape_interval: 5s
    static_configs:
      - targets: ["kafka-exporter:9308"]
        labels:
          "instance": kafka-exporter-0
