{
 "title": "Kafka Monitor",
 "description": "Kafka resource usage and throughput",
 "tags": [ "Kafka" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(kafka_brokers, job)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(kafka_brokers{job=~\"$job\"}, instance)"
    }
   },
   {
    "name": "consumergroup",
    "label": "ConsumerGroup",
    "query": {
     "query": "label_values(kafka_consumergroup_current_offset{instance=~'$instance'}, consumergroup)"
    }
   },
   {
    "name": "topic",
    "label": "Topic",
    "query": {
     "query": "label_values(kafka_consumergroup_current_offset{instance=~'$instance',consumergroup=~'$consumergroup'}, topic)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Lag by  Consumer Group",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "# 查处出正在被实例使用的消费组 (member 数量 > 0)\ngroup by(consumergroup) (kafka_consumergroup_members{instance=~\"$instance\"} > 0)\n* on(consumergroup)\ngroup_right\n# 右连接 topic 消费堆积情况\nsum by(consumergroup,instance, topic) (kafka_consumergroup_lag{instance=~\"$instance\",consumergroup=~\"$consumergroup\",topic=~\"$topic\"})\n",
     "legendFormat": "{{consumergroup}} (topic: {{topic}} instance={{instance}})"
    }
   ]
  },
  {
   "title": "Message in per second",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_topic_partition_current_offset{instance=~\"$instance\", topic=~\"$topic\"}[1m])) by (topic,instance)\n",
     "legendFormat": "{{topic}} ({{instance}})"
    }
   ]
  },
  {
   "title": "Message consume per second",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_consumergroup_current_offset{instance=~'$instance',consumergroup=~'$consumergroup',topic=~\"$topic\"}[1m])) by (consumergroup, topic)\n\n\n",
     "legendFormat": "{{consumergroup}} (topic: {{topic}})"
    }
   ]
  },
  {
   "title": "Message in per minute",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(delta(kafka_topic_partition_current_offset{instance=~'$instance', topic=~\"$topic\"}[5m])/5) by (topic,instance)",
     "legendFormat": "{{topic}} ({{instance}})"
    }
   ]
  },
  {
   "title": "Message consume per minute",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(delta(kafka_consumergroup_current_offset{instance=~'$instance',consumergroup=~'$consumergroup',topic=~\"$topic\"}[5m])/5) by (consumergroup, topic)",
     "legendFormat": "{{consumergroup}} (topic: {{topic}})"
    }
   ]
  },
  {
   "title": "Brokers",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (instance) (kafka_brokers{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "ConsumerGroup Members",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (consumergroup) (kafka_consumergroup_members{instance=~\"$instance\",consumergroup=~\"$consumergroup\"}>0)",
     "legendFormat": "{{consumergroup}}"
    }
   ]
  },
  {
   "title": "Topic Partition Under Replication",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (topic) (kafka_topic_partition_under_replicated_partition{instance=~\"$instance\",topic=~\"$topic\"})",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Current Topic Partition Under Replication",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (topic) (kafka_topic_partition_under_replicated_partition{instance=~\"$instance\",topic=~\"$topic\"})",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Partitions per Topic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(topic) (kafka_topic_partitions{instance=~\"$instance\",topic=~\"$topic\"})",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Lag by  Consumer Group (ALL)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(instance, consumergroup, topic) (kafka_consumergroup_lag{instance=~\"$instance\",consumergroup=~\"$consumergroup\",topic=~\"$topic\"})\n",
     "legendFormat": "{{consumergroup}} (topic: {{topic}} instancd={{instance}})"
    }
   ]
  }
 ]
}