services:
  backend:
    build: ./backend
    command: >
      --subpath /py
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend
    ports:
      - "8081:8080"
    depends_on:
      - backend
