version: '3.9'

services:
  nginx:
    image: nginx:1.23.4
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf:ro"

  curl:
    image: curlimages/curl:7.86.0
    entrypoint: sh
    command: |
      -c "while true; do sleep 1; done"
    depends_on:
      nginx:
        condition: service_started
