services:
  comfyui:
    build:
      dockerfile: Dockerfile
      context: .
    restart: on-failure
    ports:
      - "8188:8188"
    volumes:
      # ref: https://github.com/ltdrdata/ComfyUI-Manager?tab=readme-ov-file#paths
      - ./ComfyUI-Manager/config.ini:/workspace/ComfyUI/user/default/ComfyUI-Manager/config.ini
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8188"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 5s
