version: '3.9'

services:
  remote-host:
    image: docker:20.10.20-dind
    command: [ "--tls=false" ]
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR: ""
      DOCKER_DRIVER: overlay2
    healthcheck:
      test: [ "CMD-SHELL", "docker ps" ]
      interval: 5s
      timeout: 3s
      retries: 5

  local-host:
    image: docker:20.10.20
    environment:
      DOCKER_HOST: "tcp://remote-host:2375"
    volumes:
      - "./demo:/demo:ro"
    working_dir: /demo
    command: |
      sh -c "while true; do sleep 1; done"
    depends_on:
      remote-host:
        condition: service_healthy
