services:
  ollama:
    image: ollama/ollama
    pull_policy: always
    restart: unless-stopped
    volumes:
      - ollama:/root/.ollama
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all

  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    pull_policy: always
    restart: unless-stopped
    volumes:
      - open-webui:/app/backend/data
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434

volumes:
  ollama:
  open-webui:
