services:
  ollama:
    restart: unless-stopped
    image: ollama/ollama
    volumes:
      - ollama:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  nginx:
    restart: unless-stopped
    image: nginx:alpine
    ports:
      - "11434:80"
    volumes:
      - ./proxy.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - ollama

volumes:
  ollama:
