version: '3.9'

services:

  telegraf:
    image: telegraf:1.22.3
    command: >
      --input-filter file
      --output-filter file:elasticsearch
    volumes:
      - ./config.toml:/etc/telegraf/telegraf.conf:ro
      - ./input.json:/data/input.log:ro
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - kafka
      - elasticsearch

  tool:
    image: sko00o/go-toolbox
    entrypoint: sh
    command: >
      -c "while true; do sleep 1; done"
    volumes:
      - ./tool-run.sh:/go/run.sh:ro
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - kafka

  kafka:
    restart: unless-stopped
    image: wurstmeister/kafka:2.12-2.5.1
    environment:
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181/kafka
      KAFKA_CREATE_TOPICS: test:1:1
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - zookeeper
  zookeeper:
    restart: unless-stopped
    image: zookeeper:3.7.1

  elasticsearch:
    image: elasticsearch:7.17.7
    environment:
      - cluster.name=es-test
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
